### ISSUE TITLE
Colours make it hard to read civ text

### ISSUE THREAD

**Issue by tobersj** [TheRexYo/Son-Of-War-Mod#1]
The colours for the civ texts are too close, it's really hard to read on my phone

**Comment by TheRexYo** [comment]
Oh! Sorry for the delay! I'll see if I can petition the main developers in Unciv to add an outline for the text or something, but in the meantime I'll replace the colors with some more contrasting ones. Thanks for the feedback!

**Comment by tobersj** [comment]
Thanks for replying! I appreciate it :)

On February 13, 2021 at 8:39 AM, TheRexYo <notifications@github.com> wrote:






Oh! Sorry for the delay! I'll see if I can petition the main developers in Unciv to add an outline for the text or something, but in the meantime I'll replace the colors with some more contrasting ones. Thanks for the feedback!

**Comment by TheRexYo** [comment]
I _think_ I have made them readable. I'm not representative of everyone though, so I'll need to ask around first.
