### ISSUE TITLE
Mod not selectable in "new game" menu

### ISSUE THREAD

**Issue by Zoogzin** [TheRexYo/Son-Of-War-Mod#5]
Lot of errors popup when i select this from the dropdown, but the real issue is that the mod won't stay selected - it just switches back to the last viable mod. I think a recent unciv update broke a lot of mods, like deciv and alpha frontier, which only started working after mod patches. Thanks for the help.

**Comment by TheRexYo** [comment]
Is this still an issue? If so, I'll get right to work again.

**Comment by Zoogzin** [comment]
I can launch a new game now, thanks!
